import naves.*

test "validar error" {
	const nc = new NaveDeCombate()
	
	assert.throwsExceptionWithMessage("La lista está vacía",{nc.primerMensajeEmitido()})

}